[build]
  publish = ".next"
  command = "npm run build"

# Environment variables are set in Netlify dashboard
# No need to override them here

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Redirect rules for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
